Repository PaloAltoNetworks/pan.dev, pull requests merged in 2022-11, with the labels that each got.

#166 [DRAFT]Update Search & Add Product to Breadcrumbs
  crumbs.json
  docusaurus.config.js
  package.json
  src/theme/DocBreadcrumbs/index.js
  src/theme/DocBreadcrumbs/styles.module.css
Labels: DO NOT MERGE

#167 Voltron cleanup
  cdl/logforwarding/api/emailprofiles.mdx
  cdl/logforwarding/api/httpsprofiles.mdx
  cdl/logforwarding/api/logforwarding.md
  cdl/logforwarding/api/syslogprofiles.mdx
  cdl/logforwarding/docs/getstarted_lf.mdx
  cdl/logforwarding/docs/home.mdx
  cdl/logforwarding/docs/https_lf
  cdl/logforwarding/docs/https_lf.mdx
  cdl/logforwarding/docs/specifylogs_lf.mdx
  cdl/logforwarding/docs/syslog_lf
  cdl/logforwarding/docs/syslog_lf.mdx
  cdl/sidebar.js
  firebase.json
  src/components/Medium/index.js
Labels: sase

#168 Update include netsec products
  .github/workflows/deploy-preview.yml
Labels: contributing

#169 Fix Prisma SD-WAN Legacy nav link
  docusaurus.config.js
Labels: bug

#170 [Documentation] Partial builds and README updates
  README.md
  products/contributing/advanced/_category_.json
  products/contributing/advanced/partial-builds.md
Labels: documentation, contributing

#172 Upgrade openapi plugin to v1.4.2
  docusaurus.config.js
  openapi-specs/cdl/logforwarding/sidebar_builder.js
  package.json
  src/css/custom.scss
  yarn.lock
Labels: enhancement

#174 Add HCL syntax highlighting
  docusaurus.config.js
Labels: terraform

#190 Optimize build pipeline
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-live.yml
  .github/workflows/deploy-preview.yml
  package.json
Labels: DO NOT MERGE

#195 Proposed refactor of 404 page layout
  package.json
  src/css/custom.scss
  src/theme/NotFound.js
  static/img/404_Page.svg
  yarn.lock
Labels: DO NOT MERGE, contributing

#184 New and Amended Terraform/Ansible Docs for mid-November!
  products/ansible/docs/panos/guides/config-xpath.mdx
  products/ansible/docs/panos/guides/csv-address-objects.mdx
  products/ansible/docs/panos/guides/import-load-config.mdx
  products/ansible/docs/panos/guides/panorama-push.mdx
  products/ansible/docs/panos/guides/upgrade-single.mdx
  products/ansible/docs/panos/guides/use-config-lock.mdx
  products/ansible/docs/panos/info/background.md
  products/ansible/docs/panos/info/connectivity.md
  products/ansible/docs/panos/info/gathered-filter.md
  products/ansible/docs/panos/intro.mdx
  products/ansible/docs/panos/reference/modules.md
  products/ansible/docs/panos/sidebars.js
  products/ansible/docs/panos/tutorials/config-networking.mdx
  products/ansible/docs/panos/tutorials/config-secpol-and-objs.mdx
  products/ansible/docs/panos/tutorials/network-interfaces.png
  products/ansible/docs/panos/tutorials/operations-checkready.mdx
  products/panos/docs/intro.md
  products/panos/docs/pan-os-php.md
  products/panos/docs/restapi.md
  products/panos/docs/xmlapi.md
  products/terraform/docs/cloudngfw/aws/_assumptions.md
  products/terraform/docs/cloudngfw/aws/guides/guide.md
  products/terraform/docs/cloudngfw/aws/info/info.md
  products/terraform/docs/cloudngfw/aws/reference/provider.md
  products/terraform/docs/cloudngfw/aws/tutorials/setup.md
  products/terraform/docs/cloudngfw/azure/_assumptions.md
  products/terraform/docs/cloudngfw/azure/tutorials/setup.md
  products/terraform/docs/panos/_assumptions.md
  products/terraform/docs/panos/_closingnotes.md
  products/terraform/docs/panos/guides/commits.md
  products/terraform/docs/panos/guides/panorama-config.mdx
  products/terraform/docs/panos/info/auditcomments.md
  products/terraform/docs/panos/info/background.md
  products/terraform/docs/panos/info/create-before-destroy.md
  products/terraform/docs/panos/info/panorama-resources.md
  products/terraform/docs/panos/info/panos-versions.md
  products/terraform/docs/panos/reference/provider.md
  products/terraform/docs/panos/tutorials/_tutorial-init.md
  products/terraform/docs/panos/tutorials/config-networking.mdx
  products/terraform/docs/panos/tutorials/config-secpol-and-objs.mdx
  products/terraform/docs/panos/tutorials/info-gather-secrules.mdx
  products/terraform/docs/panos/tutorials/info-gather-sysinfo.mdx
  products/terraform/docs/panos/tutorials/network-interfaces01.png
  products/terraform/docs/panos/tutorials/network-interfaces02.png
  products/terraform/docs/panos/tutorials/setup.mdx
  products/terraform/docs/panos/tutorials/static-routes.png
  products/terraform/docs/panos/tutorials/vrouter.png
  products/terraform/docs/panos/tutorials/zones.png
  products/terraform/sidebars.js
Labels: documentation, terraform, ansible
