Repository PaloAltoNetworks/pan.dev, pull requests merged in 2022-12, with the labels that each got.

#209 [UI] Added mobile support for EditMetaRow
  src/theme/DocItem/Footer/index.tsx
  src/theme/DocItem/Footer/styles.module.css
Labels: netsec

#206 [Enhancement] Introduce applause feedback button
  docusaurus.config.js
  package.json
  src/components/Applause/assets/hands-outline.svg
  src/components/Applause/assets/hands.svg
  src/components/Applause/assets/spark.svg
  src/components/Applause/index.js
  src/components/Applause/styles.css
  src/components/EditThisPageButton/index.js
  src/components/EditThisPageButton/styles.css
  src/components/FloatingIsland/index.js
  src/components/FloatingIsland/styles.css
  src/components/Issue/index.js
  src/components/Issue/styles.css
  src/css/custom.scss
  src/theme/DocItem/Footer/index.tsx
  src/theme/DocItem/Footer/styles.module.css
  yarn.lock
Labels: enhancement, netsec

#217 Quick Ansible landing page
  products/ansible/aap2.png
  products/ansible/ansible-paloaltonetworks.png
  products/ansible/landing.mdx
Labels: ansible

#223 Add CORS proxy to SASE auth API
  docusaurus.config.js
Labels: sase
