Repository PaloAltoNetworks/pan.dev, pull requests merged in 2023-05, with the labels that each got.

#364 [Bug] Revert to legacy method for injecting GTM
  docusaurus-plugin-gtm/index.js
  docusaurus.config.js
  firebase.json
Labels: bug, netsec, contributing

#362 [CWP-48411]: Update access-api-saas.md and add a v1 endpoint
  openapi-specs/compute/22-06/output_openapi_enriched_22_06_228.json
  openapi-specs/compute/22-12/openapi_22_12_704_sorted.json
  openapi-specs/compute/30-00/openapi_30_00_140_sorted.json
  openapi-specs/compute/openapi_30_01_152.json
  openapi-specs/cwpp/30-00/openapi_saas_sorted.json
  openapi-specs/cwpp/openapi_30_01_152.json
  products/compute/api/30-00/stable-endpoints.md
  products/compute/api/stable-endpoints.md
  products/prisma-cloud/api/cwpp/30-00/stable-endpoints.md
  products/prisma-cloud/api/cwpp/access-api-saas.md
  products/prisma-cloud/api/cwpp/stable-endpoints.md
Labels: documentation

#365 Maxwell Update 1: Hotfix build
  openapi-specs/compute/openapi_30_01_153.json
  openapi-specs/cwpp/openapi_30_01_152.json
Labels: documentation, cloud
