Repository PaloAltoNetworks/pan.dev, pull requests merged in 2023-01, with the labels that each got.

#194 [UI] Terraform Landing Page and Product Landing template
  docusaurus.config.js
  package.json
  src/components/ProductLandingPage/Cards/Card.js
  src/components/ProductLandingPage/Cards/Card.scss
  src/components/ProductLandingPage/Feeds/Feeds.js
  src/components/ProductLandingPage/Feeds/Feeds.scss
  src/components/ProductLandingPage/Feeds/feeds.json
  src/components/ProductLandingPage/Hero/Hero.js
  src/components/ProductLandingPage/Hero/Hero.scss
  src/components/ProductLandingPage/Modules/Modules.js
  src/components/ProductLandingPage/Modules/Modules.scss
  src/components/ProductLandingPage/Providers/Providers.js
  src/components/ProductLandingPage/Providers/Providers.scss
  src/components/ProductLandingPage/Slider/Slider.js
  src/components/ProductLandingPage/UseCases/UseCases.js
  src/components/ProductLandingPage/UseCases/UseCases.scss
  src/constants/terraform/index.js
  src/pages/terraform.js
  static/img/icons/arrow-forward.svg
  static/img/icons/external-icon.png
  static/img/product-landing/terraform/aws-logo.png
  static/img/product-landing/terraform/azure-logo.svg
  static/img/product-landing/terraform/consul-logo.png
  static/img/product-landing/terraform/feeds/stock-feed.jpg
  static/img/product-landing/terraform/feeds/terraform-feed-2.jpeg
  static/img/product-landing/terraform/gcp-logo.svg
  static/img/product-landing/terraform/panw-logo.svg
  static/img/product-landing/terraform/technology-partner-award.jpg
  static/img/product-landing/terraform/terraform-article.jpeg
  static/img/product-landing/terraform/terraform-cloud-article.jpeg
  static/img/product-landing/terraform/terraform-logo.png
  yarn.lock
Labels: enhancement, netsec

#235 [Bug] DropdownNavbarItemMobile: Cannot read properties of undefined (reading 'map')
  src/theme/NavbarItem/DropdownNavbarItem.js
Labels: bug, netsec

#234 add external API Doc links to DLP, SaaS, and Wildfire APIs
  docusaurus.config.js
Labels: netsec

#238 Add new COM story to TF landing page
  src/constants/terraform/index.js
  static/img/product-landing/terraform/cloud-op-model.png
Labels: terraform

#240 [UI] Added section to Homepage for Partner Tools
  src/pages/index.js
  src/pages/styles.module.css
  static/img/ansible-logo.png
  static/img/terraform-logo.png
Labels: terraform, ansible

#241 Limit smooth scrolling to homepage
  src/css/custom.scss
Labels: terraform

#242 [Bug] Resolve local console errors caused by React Slick Carousel
  src/components/Medium/index.js
  src/components/ProductLandingPage/Hero/Hero.js
  src/components/ProductLandingPage/Slider/Slider.js
  src/components/Slider/Slider.js
Labels: bug, netsec

#247 Upgrade and cleanup workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-live.yml
  .github/workflows/deploy-preview.yml
Labels: contributing

#246 Remove plugin-ideal-image
  docusaurus.config.js
  package.json
  src/components/Medium/index.js
  src/components/ProductLandingPage/Cards/Card.js
  src/components/ProductLandingPage/Feeds/Feeds.js
  src/pages/index.js
  src/theme/NotFound.js
  yarn.lock
Labels: bug, netsec

#250 Update yarn.lock with new registry
  package.json
  yarn.lock
Labels: contributing

#253 [Bug] Remove original Slick arrow styling
  src/components/Slider/Slider.js
  src/components/Slider/Slider.scss
Labels: bug, netsec

#258 AWS CloudNGFW Terraform Tutorial
  products/shared/_lab-guidance.md
  products/terraform/docs/cloudngfw/aws/_assumptions.md
  products/terraform/docs/cloudngfw/aws/tutorials/aws_diagram.png
  products/terraform/docs/cloudngfw/aws/tutorials/cloudwatch_logs.png
  products/terraform/docs/cloudngfw/aws/tutorials/cloudwatch_logstream_list.png
  products/terraform/docs/cloudngfw/aws/tutorials/commit_cloudngfw.mdx
  products/terraform/docs/cloudngfw/aws/tutorials/create_cloudngfws.mdx
  products/terraform/docs/cloudngfw/aws/tutorials/create_rulestack.mdx
  products/terraform/docs/cloudngfw/aws/tutorials/intro.mdx
  products/terraform/docs/cloudngfw/aws/tutorials/prepare_aws.mdx
  products/terraform/docs/cloudngfw/aws/tutorials/prepare_cloudngfw.mdx
  products/terraform/docs/cloudngfw/aws/tutorials/review.mdx
  products/terraform/docs/cloudngfw/aws/tutorials/setup.md
  products/terraform/sidebars.js
Labels: terraform
