Repository PaloAltoNetworks/pan.dev, pull requests merged in 2023-07, with the labels that each got.

#424 CSPM 23.7.2 - Added New Resource Endpoint
  openapi-specs/cspm/ArchivedAssets.json
  openapi-specs/cspm/ArchivedAssetsMicroService.json
  openapi-specs/cspm/consolidated_spec/all_endpoints.csv
  products/prisma-cloud/docs/cspm/azure-account-onboarding.md
Labels: documentation

#412 CWP-49217-Registry-Scan-Workflow
  products/prisma-cloud/docs/cwpp/view_registry_scan.md
Labels: documentation, cloud

#429 GCP Workflow Documentation
  products/prisma-cloud/docs/cspm/aws-cloud-account-onboarding.md
  products/prisma-cloud/docs/cspm/aws-cloud-organization-onboarding.md
  products/prisma-cloud/docs/cspm/azure-account-onboarding.md
  products/prisma-cloud/docs/cspm/gcp-account-onboarding.md
  static/img/gcp_onboarding_workflow.png
Labels: documentation, DO NOT MERGE

#436 Update start:cloud script and add cloud step to deploy preview workflow
  .github/workflows/deploy-preview.yml
  package.json
Labels: cloud
