Repository PaloAltoNetworks/pan.dev, pull requests merged in 2023-11, with the labels that each got.

#349 Update OpenAPI docs plugin to v2.0.0
  package.json
  src/components/Featured/Featured.scss
  src/components/HomepageBanner/HomepageBanner.scss
  src/components/HompageHero/HomepageHero.scss
  src/components/Medium/styles.module.css
  src/css/custom.scss
  src/pages/styles.module.css
  src/theme/NavbarDocItems/index.js
  yarn.lock
Labels: enhancement, DO NOT MERGE

#538 Upgrade to OpenAPI plugin stable release
  package.json
  yarn.lock
Labels: dependencies

#547 Update cortex-xdr.md
  products/splunk/docs/cortex-xdr.md
Labels: splunk
