Repository PaloAltoNetworks/pan.dev, pull requests merged in 2023-03, with the labels that each got.

#283 [UI] Landing Page Updates
  docusaurus.config.js
  src/components/Featured/index.js
  src/components/HompageHero/HomepageHero.js
  src/components/HompageHero/HomepageHero.scss
  src/pages/index.js
Labels: enhancement, netsec

#284 Update Docusaurus OpenAPI Plugin to v1.6.1
  package.json
  yarn.lock
Labels: bug, enhancement

#285 Override details markers to match Docusaurus caret
  src/css/custom.scss
Labels: enhancement

#282 Ansible PAN-OS RBAC doc
  products/ansible/docs/panos/info/background.md
  products/ansible/docs/panos/info/pan-os-rbac.md
  products/ansible/sidebars.js
Labels: ansible

#272 AWS CloudNGFW Terraform Updates
  products/cloudngfw/docs/getstarted_aws.mdx
  products/cloudngfw/sidebars.js
  products/terraform/docs/cloudngfw/aws/tutorials/commit_cloudngfw.mdx
  products/terraform/docs/cloudngfw/aws/tutorials/create_aws_routing.mdx
  products/terraform/docs/cloudngfw/aws/tutorials/create_cloudngfws.mdx
  products/terraform/docs/cloudngfw/aws/tutorials/intro.mdx
  products/terraform/docs/cloudngfw/aws/tutorials/review.mdx
  products/terraform/sidebars.js
Labels: DO NOT MERGE, terraform

#314 Added github.com to CSP to allow authors PR to work properly
  firebase.json
Labels: contributing

#317 Update Terraform Provider cards to latest version
  src/constants/terraform/index.js
Labels: netsec
