Repository PaloAltoNetworks/pan.dev, pull requests merged in 2023-02, with the labels that each got.

#252 [Enhancement] Sanitize Medium blog content to only show first paragraph
  src/components/Medium/index.js
Labels: enhancement, netsec

#260 Guide for Ansible PAN-OS NAT Migration
  products/ansible/docs/panos/info/nat_rule_v3_migration.md
  products/ansible/sidebars.js
Labels: ansible

#267 prisma cloud landing page
  src/pages/prisma-cloud.mdx
  static/img/undraw_under_construction.svg
Labels: contributing

#277 Latest version numbers for Terraform elements
  src/constants/terraform/index.js
Labels: terraform

#278 DNS Security API fixes
  docusaurus.config.js
  openapi-specs/dns-security/dns-security.yaml
Labels: netsec
