Repository PaloAltoNetworks/pan.dev, pull requests merged in 2024-08, with the labels that each got.

#715 Cloud Security Public API Documentation 24.8.1
  openapi-specs/cspm/AssetMicroService.json
  openapi-specs/cspm/Policy.json
  openapi-specs/cspm/SearchManager.json
  openapi-specs/cspm/UVEDashboardMicroService.json
Labels: documentation, cspm-api-documentation

#723 [PAN-OS Upgrade Assurance] documentation update for release: v1.0.0
  products/panos/docs/panos-upgrade-assurance/api/check_firewall.md
  products/panos/docs/panos-upgrade-assurance/api/firewall_proxy.md
  products/panos/docs/panos-upgrade-assurance/api/snapshot_compare.md
  products/panos/docs/panos-upgrade-assurance/api/utils.md
  products/panos/docs/panos-upgrade-assurance/configuration_details.mdx
  products/panos/docs/panos-upgrade-assurance/dialect.mdx
  products/panos/docs/panos-upgrade-assurance/overview.mdx
  products/panos/docs/panos-upgrade-assurance/usage_examples.mdx
Labels: netsec

#726 Upgrade OpenAPI docs plugin to v2.2.2
  package.json
  yarn.lock
Labels: chore

#731 Upgrade openapi plugin to 2.2.3
  package.json
  yarn.lock
Labels: chore

#733 Switch to swc-loader
  docusaurus.config.js
  package.json
  yarn.lock
Labels: chore

#734 Enable processing md files as commonmark
  docusaurus.config.js
Labels: chore
