Repository PaloAltoNetworks/pan.dev, pull requests merged in 2024-01, with the labels that each got.

#572 [Bug Fix] Fix build error for Terraform page blogs
  src/components/Medium/index.js
  src/components/ProductLandingPage/Feeds/Feeds.js
  src/components/ProductLandingPage/Feeds/Feeds.scss
Labels: bug

#576 Upgrade docusaurus-openapi-docs to v2.0.3
  package.json
  yarn.lock
Labels: enhancement

#562 [PAN-OS Upgrade Assurance] documentation update for release: v0.3.1
  products/panos/docs/panos-upgrade-assurance.mdx
  products/panos/docs/panos-upgrade-assurance/api/check_firewall.md
  products/panos/docs/panos-upgrade-assurance/api/firewall_proxy.md
  products/panos/docs/panos-upgrade-assurance/api/utils.md
  products/panos/docs/panos-upgrade-assurance/configuration_details.mdx
Labels: netsec

#578 Compute API removing old releases to resolve JavaScript heap out of memory error
  docusaurus.config.js
  openapi-specs/compute/22-12/openapi_22_12_704_sorted.json
  openapi-specs/compute/30-00/openapi_30_00_140_sorted.json
  products/compute/api/22-12/access-api-self-hosted.md
  products/compute/api/22-12/set-up-console.md
  products/compute/api/22-12/stable-endpoints.md
  products/compute/api/22-12/welcome-prisma-cloud-apis.md
  products/compute/api/30-00/stable-endpoints.md
  products/compute/api/30-03/welcome-prisma-cloud-apis.md
  products/compute/api/31-02/welcome-prisma-cloud-apis.md
  products/compute/sidebars.js
Labels: Compute API Ref
