Repository PaloAltoNetworks/pan.dev, pull requests merged in 2024-12, with the labels that each got.

#775 RLP-153440 Prisma Cloud API Landing Page Text
  docusaurus.config.js
Labels: cloud

#774 RLP-153443, PCSUP-24945 CSPM Azure Doc Update - Microsoft Entra ID
  products/prisma-cloud/docs/cspm/azure-account-onboarding.md
Labels: documentation, cloud, cspm-api-documentation

#788 Apply patch to schema component to workaround broken discriminators
  openapi-specs/cspm/AssetMicroService.json
  src/css/custom.scss
  src/theme/Schema/index.tsx
Labels: bug

#798 Improve error handling when fetching blog feeds
  .gitignore
  package.json
  src/components/Medium/index.js
Labels: bug

#799 Use SCM demo video as hero background
  src/pages/strata-cloud-manager/index.js
  src/pages/strata-cloud-manager/scm.scss
Labels: sase

#802 Upgrade OpenAPI docs plugin to v4.3.1
  package.json
  yarn.lock
Labels: DO NOT MERGE
