Repository PaloAltoNetworks/pan.dev, pull requests merged in 2025-07, with the labels that each got.

#950 upgrade docusaurus to v3.8.1 and plugin to v4.5.1
  docusaurus.config.ts
  package.json
  plugin-sitemap-coveo/package.json
  src/css/custom.scss
  yarn.lock
Labels: chore

#951 P4: AIRS APIs updates
  docusaurus.config.ts
  openapi-specs/prisma-airs/scan/ScanService.yaml
  products/prisma-airs/api/airuntimesecurity/airuntimesecurityapi.md
  products/prisma-airs/api/airuntimesecurity/usecases.md
Labels: DO NOT MERGE, Prisma AIRS

#957 Update pythonsdk and Error Codes
  products/prisma-airs/api/airuntimesecurity/airuntimesecurityapi.md
  products/prisma-airs/api/airuntimesecurity/errorcodes.md
  products/prisma-airs/api/airuntimesecurity/pythonsdk.md
  products/prisma-airs/api/airuntimesecurity/pythonsdkasynciousage.md
  products/prisma-airs/api/airuntimesecurity/pythonsdkusage.md
  products/prisma-airs/api/airuntimesecurity/usecases.md
  products/prisma-airs/sidebars.ts
Labels: Prisma AIRS

#965 chore: cleanup applause component, deps and references
  docusaurus.config.ts
  package.json
  src/components/Applause/assets/hands-outline.svg
  src/components/Applause/assets/hands.svg
  src/components/Applause/assets/spark.svg
  src/components/Applause/index.js
  src/components/Applause/styles.css
  src/components/FloatingIsland/index.js
  src/theme/DocItem/Footer/index.tsx
  yarn.lock
Labels: netsec, contributing, chore

#966 filter out ChunkLoadError exceptions
  src/theme/Root.js
Labels: netsec, contributing, chore

#968 RLP-156670 remove orphaned Twistcli getting started document.
  products/prisma-cloud/docs/twistcli_gs.md
Labels: documentation, cloud, prismacloud-api-documentation

#973 Fork/master
  docusaurus.config.ts
  openapi-specs/dlp/DLPAPI(Beta).yaml
  openapi-specs/dlp/DLPAPI.yaml
Labels: review

#974 Fork/master
  openapi-specs/dlp/DLPAPI(Beta).yaml
  openapi-specs/dlp/DLPAPI.yaml
Labels: review
