Repository PaloAltoNetworks/pan.dev, pull requests merged in 2025-06, with the labels that each got.

#925 Revert default list-style
  src/css/custom.scss
Labels: bug, netsec

#926 BAN-22100: Adding Public API Documentation for new IOT Public APIs - CRUD APIs for Subnets, Network Segments, and Sites Tables
  openapi-specs/iot/api/public/createNetworkSegment.yaml
  openapi-specs/iot/api/public/createSite.yaml
  openapi-specs/iot/api/public/createSubnet.yaml
  openapi-specs/iot/api/public/deleteNetworkSegment.yaml
  openapi-specs/iot/api/public/deleteSite.yaml
  openapi-specs/iot/api/public/deleteSubnet.yaml
  openapi-specs/iot/api/public/getNetworkSegment.yaml
  openapi-specs/iot/api/public/getSite.yaml
  openapi-specs/iot/api/public/getSubnet.yaml
  openapi-specs/iot/api/public/revertSubnet.yaml
  openapi-specs/iot/api/public/transferSubnet.yaml
  openapi-specs/iot/api/public/updateNetworkSegment.yaml
  openapi-specs/iot/api/public/updateSite.yaml
  openapi-specs/iot/api/public/updateSubnet.yaml
  openapi-specs/iot/components/examples.yaml
  openapi-specs/iot/components/schemas.yaml
  openapi-specs/iot/iot.yaml
Labels: netsec

#917 Pythonsdk update
  products/ai-runtime-security/api/pythonsdk.md
  products/ai-runtime-security/api/pythonsdkasynciousage.md
  products/ai-runtime-security/api/pythonsdkusage.md
  products/ai-runtime-security/api/usecases.md
  products/ai-runtime-security/sidebars.ts
Labels: AI Runtime Security

#932 Rebrand AI Runtime Security to Prisma AIRS
  docusaurus.config.ts
  openapi-specs/prisma-airs/scan/ScanService.yaml
  package.json
  products/ai-runtime-security/api/airuntimesecurityapi.md
  products/ai-runtime-security/sidebars.ts
  products/prisma-airs/api/airuntimesecurity/airuntimesecurityapi.md
  products/prisma-airs/api/airuntimesecurity/pythonsdk.md
  products/prisma-airs/api/airuntimesecurity/pythonsdkasynciousage.md
  products/prisma-airs/api/airuntimesecurity/pythonsdkusage.md
  products/prisma-airs/api/airuntimesecurity/usecases.md
  products/prisma-airs/docs/home.md
  products/prisma-airs/sidebars.ts
  src/components/UseCasesTabs.js
  src/components/UseCasesTabs.jsx
  src/pages/airs/index.js
Labels: DO NOT MERGE, netsec, Prisma AIRS

#941 move and update plugin-sitemap-coveo manifest
  plugin-sitemap-coveo/package.json
  plugin-sitemap-coveo/src/package.json
Labels: bug, contributing

#945 feat(ci): add support for dynamic PRODUCTS_INCLUDE builds
  .github/workflows/deploy-preview.yml
  scripts/get-changed-products.js
Labels: enhancement, contributing
