Repository PaloAltoNetworks/pan.dev, pull requests merged in 2025-04, with the labels that each got.

#877 Runner
  .github/workflows/codeql-analysis.yml
Labels: review

#878 Run codeql on ubuntu-latest
  .github/workflows/deploy-preview.yml
Labels: review

#883 [WebUI] Add missing tab index to Copy for AI button
  src/components/CopyButton/index.js
  src/components/Tooltip/index.js
Labels: bug

#887 [UI Enhancement] Landing Page Refresh v2
  package.json
  postcss.config.js
  src/components/AceternityUI/AnimatedTabs.js
  src/components/AceternityUI/AnimatedTestimonials.js
  src/components/AceternityUI/DotBackground.js
  src/components/AceternityUI/DotBackground.scss
  src/components/AceternityUI/FlipWords.js
  src/components/AceternityUI/FlipWords.scss
  src/components/AceternityUI/Hero.js
  src/components/AceternityUI/PartnerTools.js
  src/components/AceternityUI/PartnerTools.scss
  src/components/AceternityUI/Tabs.js
  src/components/AceternityUI/Tabs.scss
  src/components/HomepageBanner/HomepageBanner.js
  src/components/HomepageBanner/HomepageBanner.scss
  src/components/Medium/BlogCard.css
  src/components/Medium/BlogCard.js
  src/components/Medium/Slider.scss
  src/components/Medium/index.js
  src/components/Slider/Slider.js
  src/css/custom.scss
  src/hooks/useHtmlDataTheme.js
  src/pages/index.js
  src/util.js
  static/img/homepage-tabs/APIReferenceExample.png
  static/img/homepage-tabs/DeveloperDocsExample.png
  static/img/homepage-tabs/GettingStartedExample.png
  yarn.lock
Labels: contributing

#889 Move to custom blog parser/converter
  package.json
  scripts/feed2json.js
  src/components/Medium/index.js
  src/components/ProductLandingPage/Feeds/Feeds.js
  yarn.lock
Labels: contributing
